spring:
  application:
    name: store

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 22the333

  jwt:
    secret: ${JWT_SECRET}

    accessTokenExpiration: 3000 # 5m
    refreshTokenExpiration: 604800 #7d